{% set name = "pyramid" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 45431b387587ed0fac6213b54d6e9f0936f0cc85238a8f5af7852fc9484c5c77

build:
  noarch: python
  number: 0
  entry_points:
    - pserve=pyramid.scripts.pserve:main
    - pshell=pyramid.scripts.pshell:main
    - proutes=pyramid.scripts.proutes:main
    - pviews=pyramid.scripts.pviews:main
    - ptweens=pyramid.scripts.ptweens:main
    - prequest=pyramid.scripts.prequest:main
    - pdistreport=pyramid.scripts.pdistreport:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - hupper >=1.5
    - plaster
    - plaster_pastedeploy
    - translationstring >=0.4
    - venusian >=1.0
    - webob >=1.8.3
    - zope.deprecation >=3.5.0
    - zope.interface >=3.8.0

test:
  imports:
    - pyramid
    - pyramid.config
    - pyramid.scripts
  commands:
    - pserve --help
    - pshell --help
    - proutes --help
    - pviews --help
    - ptweens --help
    - prequest --help
    - pdistreport --help

about:
  home: https://trypyramid.com
  license: LicenseRef-Pylons AND BSD-like AND ZPL-2.1
  license_family: BSD
  license_file: LICENSE.txt
  summary: The Pyramid Web Framework, a Pylons project
  description: |
    As a framework, its primary job is to make it easier for a developer to create an arbitrary
    web application. The type of application being created isn't really
    important; it could be a spreadsheet, a corporate intranet, or a social
    networking platform.
  doc_url: https://docs.pylonsproject.org/projects/pyramid/
  dev_url: https://github.com/Pylons/pyramid

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - ChrisBarker-NOAA